language: java
script: 
  - mvn clean verify
  - echo "$LOGIN" | docker login -u "$PASSWORD" --password-stdin
  - docker build -t changelog sample-application-db-changelog-job/
  - docker tag changelog changelog
  - docker push changelog
cache:
  directories:
    - $HOME/.m2
services:
  - docker
